### ISSUE TITLE
iRacingSDK.DataSample.Telemetry.Cars[n] properties "HasSeenCheckeredFlag" and "HasRetired" throw NullReferenceException

### ISSUE THREAD

**Issue by Sk93** [MerlinCooper/iRacingSDK.Net#5]
Pretty much as the title.

These are set as non-nullable fields, which occasionally causes them to throw a NullReferenceException.

Maybe change lines 78 and 80 of "Car.cs" to gracefully handle the array lookup being null?

public bool HasRetired { get { return telemetry.HasRetired!=null ? telemetry.HasRetired[carIdx] : false; } }

or turn the props to nullable type?
![null error](https://user-images.githubusercontent.com/3426792/108719121-1ad81b00-7517-11eb-8b9f-f8838ba59e75.png)

**Comment by MerlinCooper** [comment]
@Sk93 I know it's been a long time ago that you raised this issue. For sure making a nullable value would be the optimal solution but I'm a little bit concerned how much of changes would be required for applications using the NuGet - if there is still someone using it. 

At the end I did implement pretty much your recommendation - except that I picked as default response for HasRetired true instead of false, because most likely there is no data anymore for a driver/car when the left the session. 

```
public bool HasSeenCheckeredFlag { get { return telemetry.HasSeenCheckeredFlag != null ? telemetry.HasSeenCheckeredFlag[carIdx] : false; } }
public bool HasRetired { get { return telemetry.HasRetired != null ? telemetry.HasRetired[carIdx] : true; } }
```

Updated code can be found in a [separate branch.](https://github.com/MerlinCooper/iRacingSDK.Net/tree/5-iracingsdkdatasampletelemetrycarsn-properties-hasseencheckeredflag-and-hasretired-throw-nullreferenceexception
) . Will wait one or the other week before I merge that to the master branch and the nuget gets updates.
